import {
  CampaignNode,
  CampaignEdge,
  Claim,
  Source,
  CanonEntry,
  Session,
  LooseEnd,
  AuditEvent,
  User,
} from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'cooper',
    name: 'Agente Cooper',
    role: 'anfitrion',
    badge: 'GM-AUTH-00',
    title: 'Anfitrión de Actas & Custodio del Grafo',
    proposalsCount: 2,
    approvedCanonCount: 2,
    presentationsCount: 1,
  },
  {
    id: 'carlos',
    name: 'Carlos M.',
    role: 'jugador',
    badge: 'AGENT-FIELD-01',
    title: 'Investigador de Terreno & Balística',
    proposalsCount: 3,
    approvedCanonCount: 1,
    presentationsCount: 2,
  },
  {
    id: 'sofia',
    name: 'Sofía G.',
    role: 'jugador',
    badge: 'AGENT-CRYPT-02',
    title: 'Criptología & Señales Electromagnéticas',
    proposalsCount: 2,
    approvedCanonCount: 2,
    presentationsCount: 1,
  },
  {
    id: 'elena',
    name: 'Elena R.',
    role: 'jugador',
    badge: 'AGENT-ARCH-03',
    title: 'Archivista Forense & Registros NARA',
    proposalsCount: 3,
    approvedCanonCount: 3,
    presentationsCount: 1,
  },
  {
    id: 'lucas',
    name: 'Lucas V.',
    role: 'jugador',
    badge: 'AGENT-CHRONO-04',
    title: 'Cronología Comparada & Fuentes Ocultas',
    proposalsCount: 2,
    approvedCanonCount: 2,
    presentationsCount: 1,
  },
  {
    id: 'espectador',
    name: 'Auditor Externo',
    role: 'espectador',
    badge: 'OBS-AUDIT-05',
    title: 'Observador de Sala Presencial',
    proposalsCount: 0,
    approvedCanonCount: 0,
    presentationsCount: 0,
  },
];

export const INITIAL_NODES: CampaignNode[] = [
  {
    id: 'N01',
    code: 'EXP-N01',
    name: 'Operación Paperclip',
    shortName: 'Op. Paperclip',
    type: 'acontecimiento',
    truthLayer: 'HECHO',
    category: 'Aeroespacial / Militar',
    neutralDescription:
      'Traslado clandestino de especialistas en aeronáutica y balística alemanes a laboratorios de White Sands y Fort Bliss en 1945.',
    tags: ['NARA RG-330', 'Von Braun', '1945', 'White Sands'],
    sensitivity: 'media',
    status: 'canonizado',
    x: 180,
    y: 160,
    cluster: 'historia',
    speakerId: 'carlos',
    speakerName: 'Carlos M.',
    sessionId: 'S01',
    historicalPeriod: '1945 - 1959',
    centralityScore: 0.65,
    directLinksCount: 3,
    secondHopCount: 7,
  },
  {
    id: 'N02',
    code: 'EXP-N02',
    name: 'Proyecto MKUltra & Subproyecto 68',
    shortName: 'Proyecto MKUltra',
    type: 'tecnología',
    truthLayer: 'HECHO',
    category: 'Control Mental / Psicología',
    neutralDescription:
      'Subproyecto 68 conducido en el Allan Memorial Institute de Montreal sobre privación sensorial, frecuencias binaurales y borrado psíquico.',
    tags: ['Senado 1977', 'Dr. Cameron', 'Sidney Gottlieb', 'Montreal'],
    sensitivity: 'alta',
    status: 'canonizado',
    x: 340,
    y: 250,
    cluster: 'mente',
    speakerId: 'sofia',
    speakerName: 'Sofía G.',
    sessionId: 'S02',
    historicalPeriod: '1953 - 1973',
    centralityScore: 0.78,
    directLinksCount: 5,
    secondHopCount: 11,
  },
  {
    id: 'N03',
    code: 'EXP-N03',
    name: 'Incidente Roswell & Wright-Patterson',
    shortName: 'Roswell Base',
    type: 'acontecimiento',
    truthLayer: 'AFIRMACIÓN',
    category: 'Aeronáutica Anómala',
    neutralDescription:
      'Recuperación de restos materiales no identificados en el rancho Foster (Nuevo México, julio de 1947) y custodia por la División Técnica de Vuelo.',
    tags: ['Hangar 18', '1947', 'Aleación con memoria', 'FOIA'],
    sensitivity: 'alta',
    status: 'canonizado',
    x: 520,
    y: 220,
    cluster: 'aeroespacial',
    speakerId: 'carlos',
    speakerName: 'Carlos M.',
    sessionId: 'S03',
    historicalPeriod: '1947',
    centralityScore: 0.81,
    directLinksCount: 6,
    secondHopCount: 14,
  },
  {
    id: 'N04',
    code: 'EXP-N04',
    name: 'Transmisor Montauk & Silla PSI',
    shortName: 'Transmisor Montauk',
    type: 'teoría',
    truthLayer: 'AFIRMACIÓN',
    category: 'Guerra Psicotrónica',
    neutralDescription:
      'Antena radar militar SAGE AN/FPS-35 en Camp Hero (Montauk Point). Frecuencia UHF de 425-450 MHz interconectada con experimentos de resonancia craneal y curvatura temporal.',
    tags: ['Camp Hero', '425 MHz', 'Silla PSI', '1983'],
    sensitivity: 'restringida',
    status: 'asignado',
    x: 680,
    y: 340,
    cluster: 'montauk',
    photoUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuABAKxJ9688b1tOU7LZVWo4xwLjp-c0S-RZqw0ARKY7zvgY_3A7K0fvmL92PCPBq0G_oO25LFj9GvT61EyvXxKN7qQ7hWsIMiOB6v2r4XsItfx6DjK4v6o5ggddKX7CaX0nrMAUpMZLPcNGAPcK40l4ORRnOpu14MboJosSKd6a9AYWKMmEmCCiiLn4AY5oWfJHHDeIo-d_tbFpAKpLi2cMl5aBJJRWddxSlMXpWF4feAUSnrVkCI91',
    photoCaption: 'Antena radar AN/FPS-35 en Camp Hero (Long Island, NY). Desclasificado NARA 1982.',
    speakerId: 'carlos',
    speakerName: 'Carlos M.',
    sessionId: 'S04',
    historicalPeriod: '1982 - 1989',
    centralityScore: 0.84,
    directLinksCount: 8,
    secondHopCount: 19,
  },
  {
    id: 'N05',
    code: 'EXP-N05',
    name: 'Bohemian Grove: Cónclave de Monte Río',
    shortName: 'Bohemian Grove',
    type: 'organización',
    truthLayer: 'HECHO',
    category: 'Élites & Simbolismo',
    neutralDescription:
      'Campamento forestal de 11 km² en Sonoma County donde líderes gubernamentales y corporativos celebran la ceremonia "Cremation of Care" ante una efigie de búho de 12 metros.',
    tags: ['Sonoma', 'Cremation of Care', 'Búho de Minerva', 'Manhattan Project'],
    sensitivity: 'media',
    status: 'candidato',
    x: 600,
    y: 90,
    cluster: 'sociedades',
    historicalPeriod: '1899 - Presente',
    centralityScore: 0.58,
    directLinksCount: 4,
    secondHopCount: 9,
  },
  {
    id: 'N06',
    code: 'EXP-N06',
    name: 'Señal Wow! y Radiotelescopio Big Ear',
    shortName: 'Señal Wow! (1977)',
    type: 'acontecimiento',
    truthLayer: 'HECHO',
    category: 'Radioastronomía / SETI',
    neutralDescription:
      'Emisión de radio anómala de banda estrecha (1420.455 MHz) detectada el 15 de agosto de 1977 por Jerry Ehman en Ohio State University. Frecuencia de la línea de hidrógeno.',
    tags: ['1420 MHz', 'Big Ear', 'Jerry Ehman', 'SETI'],
    sensitivity: 'baja',
    status: 'candidato',
    x: 780,
    y: 490,
    cluster: 'senales',
    historicalPeriod: '1977',
    centralityScore: 0.52,
    directLinksCount: 3,
    secondHopCount: 8,
  },
  {
    id: 'N07',
    code: 'EXP-N07',
    name: 'Iniciativa Majestic 12 (MJ-12)',
    shortName: 'Majestic 12',
    type: 'documento',
    truthLayer: 'AFIRMACIÓN',
    category: 'Gobierno en la Sombra',
    neutralDescription:
      'Supuesto comité ejecutivo secreto de 12 científicos, mandos militares y directores de inteligencia creado en 1947 por orden ejecutiva del presidente Harry S. Truman.',
    tags: ['Cutler-Twining', 'Forrestal', 'SOM1-01', 'Van Bush'],
    sensitivity: 'alta',
    status: 'candidato',
    x: 490,
    y: 440,
    cluster: 'aeroespacial',
    historicalPeriod: '1947 - 1984',
    centralityScore: 0.72,
    directLinksCount: 5,
    secondHopCount: 12,
  },
  {
    id: 'N08',
    code: 'EXP-N08',
    name: 'Red ECHELON y Convenio UKUSA',
    shortName: 'Red ECHELON',
    type: 'tecnología',
    truthLayer: 'HECHO',
    category: 'Vigilancia Global',
    neutralDescription:
      'Red de interceptación electromagnética operada por los "Five Eyes" (EE.UU., Reino Unido, Canadá, Australia y Nueva Zelanda) para rastrear satélites Intelsat y cables submarinos.',
    tags: ['Five Eyes', 'Menwith Hill', 'Satélites', 'NSA'],
    sensitivity: 'media',
    status: 'disponible',
    x: 420,
    y: 600,
    cluster: 'senales',
    historicalPeriod: '1948 - Presente',
    centralityScore: 0.69,
    directLinksCount: 4,
    secondHopCount: 10,
  },
  {
    id: 'N09',
    code: 'EXP-N09',
    name: 'Explosión de Tunguska (1908)',
    shortName: 'Evento Tunguska',
    type: 'acontecimiento',
    truthLayer: 'HECHO',
    category: 'Cataclismos Anómalos',
    neutralDescription:
      'Detonación aérea de aproximadamente 12 megatones en Podkamennaya Tunguska (Siberia) que arrasó 80 millones de árboles en 2.150 km² sin cráter de impacto descubierto.',
    tags: ['Siberia', '1908', 'Kulik', 'Microbarógrafo'],
    sensitivity: 'baja',
    status: 'bloqueado',
    x: 180,
    y: 560,
    cluster: 'geo',
    historicalPeriod: '1908',
    centralityScore: 0.35,
    directLinksCount: 2,
    secondHopCount: 4,
  },
  {
    id: 'N10',
    code: 'EXP-N10',
    name: 'Instalación S-4 y Groom Lake (Área 51)',
    shortName: 'Complejo S-4',
    type: 'lugar',
    truthLayer: 'AFIRMACIÓN',
    category: 'Ingeniería Inversa',
    neutralDescription:
      'Instalación subterránea en Papoose Lake (Nevada) presuntamente destinada a la retroingeniería de reactores antimateria de elemento 115.',
    tags: ['Bob Lazar', 'Elemento 115', 'Papoose Lake', 'DOD'],
    sensitivity: 'restringida',
    status: 'no_explorado',
    x: 640,
    y: 680,
    cluster: 'aeroespacial',
    historicalPeriod: '1989',
    centralityScore: 0.61,
    directLinksCount: 3,
    secondHopCount: 8,
  },
  {
    id: 'N11',
    code: 'EXP-N11',
    name: 'Programa Espacial Secreto (Solar Warden)',
    shortName: 'Solar Warden',
    type: 'teoría',
    truthLayer: 'AFIRMACIÓN',
    category: 'Flota No Terrestre',
    neutralDescription:
      'Presunta flota orbital militar de la Marina de EE.UU. revelada por Gary McKinnon tras piratear terminales del Comando Espacial en 2002.',
    tags: ['Gary McKinnon', '2002', 'Non-terrestrial officers', 'US Navy'],
    sensitivity: 'restringida',
    status: 'no_explorado',
    x: 820,
    y: 210,
    cluster: 'aeroespacial',
    historicalPeriod: '1980 - 2002',
    centralityScore: 0.44,
    directLinksCount: 2,
    secondHopCount: 6,
  },
  {
    id: 'N12',
    code: 'EXP-N12',
    name: 'Portales Telúricos en Niebla de Glastonbury',
    shortName: 'Portales Glastonbury',
    type: 'esotérico',
    truthLayer: 'CANON',
    category: 'Metafísica de Campaña',
    neutralDescription:
      'Coincidencia geográfica de nodos ley y oscilaciones electromagnéticas registradas en la cabaña del lago Glastonbury, vinculadas a la sintonía Montauk por la mesa.',
    tags: ['Líneas Ley', 'Glastonbury', 'Canon de Sala', 'Cabaña'],
    sensitivity: 'media',
    status: 'candidato',
    x: 580,
    y: 580,
    cluster: 'geo',
    historicalPeriod: 'Canon 1989',
    centralityScore: 0.41,
    directLinksCount: 2,
    secondHopCount: 5,
  },
  {
    id: 'N13',
    code: 'EXP-N13',
    name: 'Proyecto Star Gate y Visión Remota (SRI)',
    shortName: 'Star Gate / SRI',
    type: 'tecnología',
    truthLayer: 'HECHO',
    category: 'Guerra Psicotrónica',
    neutralDescription:
      'Unidad de espionaje psíquico financiada por CIA/DIA en el Stanford Research Institute con Russell Targ, Hal Puthoff e Ingo Swann.',
    tags: ['Ingo Swann', 'SRI', '1978', 'Desclasificado 1995'],
    sensitivity: 'media',
    status: 'disponible',
    x: 250,
    y: 380,
    cluster: 'mente',
    historicalPeriod: '1972 - 1995',
    centralityScore: 0.63,
    directLinksCount: 4,
    secondHopCount: 9,
  },
  {
    id: 'N14',
    code: 'EXP-N14',
    name: 'Operación Highjump y Bases Antárticas',
    shortName: 'Op. Highjump',
    type: 'acontecimiento',
    truthLayer: 'AFIRMACIÓN',
    category: 'Expediciones Militares',
    neutralDescription:
      'Misión antártica naval de la US Navy (Task Force 68) en 1946-1947 con 4.700 efectivos y 13 navíos comandada por el contralmirante Richard E. Byrd.',
    tags: ['Almirante Byrd', '1947', 'Neuschwabenland', 'Tierra Hueca'],
    sensitivity: 'media',
    status: 'no_explorado',
    x: 90,
    y: 420,
    cluster: 'geo',
    historicalPeriod: '1946 - 1947',
    centralityScore: 0.48,
    directLinksCount: 2,
    secondHopCount: 5,
  },
];

export const INITIAL_EDGES: CampaignEdge[] = [
  {
    id: 'E01',
    fromNodeId: 'N01',
    toNodeId: 'N02',
    type: 'deriva de',
    direction: 'unidireccional',
    explanation:
      'Los protocolos de condicionamiento y desprogramación conductual en White Sands fueron asimilados por la división química de MKUltra.',
    sourceRef: 'Expediente NARA RG-330 / Audiencia Senado 1977',
    creativeLicense: 'ninguna',
    isPlayedThread: true,
    sessionId: 'S01',
  },
  {
    id: 'E02',
    fromNodeId: 'N02',
    toNodeId: 'N03',
    type: 'comparte personajes',
    direction: 'bidireccional',
    explanation:
      'Científicos del Subproyecto 68 fueron consultados en Wright-Patterson para examinar la respuesta neurocognitiva a materiales meméticos.',
    sourceRef: 'Memorándum de Enlace AFOSR-1953',
    creativeLicense: 'ninguna',
    isPlayedThread: true,
    sessionId: 'S02',
  },
  {
    id: 'E03',
    fromNodeId: 'N03',
    toNodeId: 'N04',
    type: 'puente narrativo',
    direction: 'unidireccional',
    explanation:
      'La antena de radar de Camp Hero fue recalibrada utilizando aleaciones magnéticas provenientes de los depósitos de Wright-Patterson.',
    sourceRef: 'Bitácora técnica de radar SAGE (1983)',
    creativeLicense: 'ninguna',
    isPlayedThread: true,
    sessionId: 'S03',
  },
  {
    id: 'E04',
    fromNodeId: 'N04',
    toNodeId: 'N05',
    type: 'comparte acontecimiento',
    direction: 'bidireccional',
    explanation:
      'Conexión directa (1 salto elegible): Contratistas de microondas de Montauk asistieron a los cónclaves de verano de Bohemian Grove en 1983.',
    sourceRef: 'Lista de asistentes filtrada Bohemian Club 1983',
    creativeLicense: 'ninguna',
    isPlayedThread: false,
  },
  {
    id: 'E05',
    fromNodeId: 'N04',
    toNodeId: 'N07',
    type: 'se asocia con',
    direction: 'bidireccional',
    explanation:
      'Conexión directa (1 salto elegible): Financiación no auditada de Montauk autorizada mediante partidas clandestinas atribuidas al comité MJ-12.',
    sourceRef: 'Auditoría GAO-84-LONGISLAND',
    creativeLicense: 'ninguna',
    isPlayedThread: false,
  },
  {
    id: 'E06',
    fromNodeId: 'N04',
    toNodeId: 'N06',
    type: 'puente narrativo',
    direction: 'bidireccional',
    explanation:
      'Puente de dos saltos (Requiere justificación): Sincronización armónica entre la frecuencia de 425 MHz de Montauk y el armónico de 1420 MHz de la Señal Wow! captada en Ohio.',
    sourceRef: 'Revista de Radioastronomía & Telemetría (1978)',
    creativeLicense: 'dispensa_aprobada',
    isPlayedThread: false,
  },
  {
    id: 'E07',
    fromNodeId: 'N02',
    toNodeId: 'N08',
    type: 'se asocia con',
    direction: 'unidireccional',
    explanation:
      'Intercepción de telecomunicaciones de ECHELON alimentó las bases de datos de perfiles psicológicos de MKUltra.',
    sourceRef: 'Informe Duncan Campbell (1988)',
    creativeLicense: 'ninguna',
    isPlayedThread: false,
  },
  {
    id: 'E08',
    fromNodeId: 'N08',
    toNodeId: 'N04',
    type: 'puente narrativo',
    direction: 'bidireccional',
    explanation:
      'Ruta puente de 2 saltos: ECHELON interceptó las alertas de interferencia electromagnética de Montauk hacia navíos del Atlántico Norte.',
    sourceRef: 'Acta de la Guardia Costera de Long Island (1984)',
    creativeLicense: 'dispensa_aprobada',
    isPlayedThread: false,
  },
  {
    id: 'E09',
    fromNodeId: 'N07',
    toNodeId: 'N10',
    type: 'deriva de',
    direction: 'unidireccional',
    explanation:
      'La seguridad y custodia de las naves en S-4 depende de directivas de compartimentación originadas en Majestic-12.',
    sourceRef: 'Manual SOM1-01 (disputado)',
    creativeLicense: 'requiere_licencia',
    isPlayedThread: false,
  },
  {
    id: 'E10',
    fromNodeId: 'N04',
    toNodeId: 'N12',
    type: 'conexión creada por el grupo',
    direction: 'bidireccional',
    explanation:
      'Canon de asamblea: El sintetizador acústico hallado en la cabaña de Glastonbury resonaba en la misma longitud de onda que el pulso Montauk.',
    sourceRef: 'Acta Sesión #03 (Lucas V.)',
    creativeLicense: 'ninguna',
    isPlayedThread: false,
  },
];

export const INITIAL_SESSIONS: Session[] = [
  {
    id: 'S01',
    seasonId: 'T01',
    number: '01',
    title: 'El Pacto del Sótano: De Peenemünde a White Sands',
    date: '28 Sep 2026',
    hostName: 'Agente Cooper',
    presenterId: 'carlos',
    presenterName: 'Carlos M.',
    presenterRole: 'Investigador de Terreno',
    mainNodeId: 'N01',
    mainNodeName: 'Operación Paperclip',
    status: 'cerrada',
    summary:
      'Apertura de campaña. Se revisaron expedientes desclasificados sobre los 1.600 científicos trasladados por el Joint Intelligence Objectives Agency. Se votó por unanimidad el Canon-01 sobre nóminas paralelas sin sello oficial.',
    durationMin: 22,
    slidesUrl: 'https://docs.google.com/presentation/d/demo-s01',
    slideCount: 18,
    routeUsedSummary: 'Nodo Inicial [N-01]',
    cliffhanger:
      '¿Qué contenía la caja sellada enviada desde Fort Bliss a la Universidad McGill en el invierno de 1951?',
    nextProposedNodeIds: ['N02', 'N14'],
  },
  {
    id: 'S02',
    seasonId: 'T01',
    number: '02',
    title: 'Eco Binaural Montreal: La Frecuencia del Olvido',
    date: '05 Oct 2026',
    hostName: 'Agente Cooper',
    presenterId: 'sofia',
    presenterName: 'Sofía G.',
    presenterRole: 'Criptología',
    mainNodeId: 'N02',
    mainNodeName: 'Proyecto MKUltra',
    status: 'cerrada',
    summary:
      'Exposición sobre el Subproyecto 68 en el Allan Memorial Institute. Se analizaron las transcripciones de las sesiones de desprogramación con electroshock cíclico. Moción de Canon-02 aprobada con 4 votos a favor.',
    durationMin: 26,
    slidesUrl: 'https://docs.google.com/presentation/d/demo-s02',
    slideCount: 22,
    routeUsedSummary: 'N-01 -> N-02 (Deriva directa)',
    cliffhanger:
      '¿Por qué las cintas de audio repetían las coordenadas geográficas del polígono de pruebas de Alamogordo?',
    nextProposedNodeIds: ['N03', 'N08', 'N13'],
  },
  {
    id: 'S03',
    seasonId: 'T01',
    number: '03',
    title: 'Cráter & Aleaciones: La Materia Memética de Wright-Patterson',
    date: '12 Oct 2026',
    hostName: 'Agente Cooper',
    presenterId: 'elena',
    presenterName: 'Elena R.',
    presenterRole: 'Archivista Forense',
    mainNodeId: 'N03',
    mainNodeName: 'Incidente Roswell',
    status: 'cerrada',
    summary:
      'Inspección de las declaraciones contradictorias de la Oficina de Prensa del 509th Bomb Group. Enmienda formal a Canon-02 y aprobación de Canon-03 sobre la naturaleza de la aleación metálica recuperada.',
    durationMin: 28,
    slidesUrl: 'https://docs.google.com/presentation/d/demo-s03',
    slideCount: 24,
    routeUsedSummary: 'N-02 -> N-03 (Personajes compartidos)',
    cliffhanger:
      '¿Hacia qué instalación costera de Long Island se despacharon los magnetrones blindados de 425 MHz en 1982?',
    nextProposedNodeIds: ['N04', 'N07'],
  },
  {
    id: 'S04',
    seasonId: 'T01',
    number: '04',
    title: 'El Transmisor de Montauk y el Experimento Filadelfia',
    date: '18 Oct 2026',
    hostName: 'Agente Cooper',
    presenterId: 'carlos',
    presenterName: 'Carlos M.',
    presenterRole: 'Investigador de Terreno',
    mainNodeId: 'N04',
    mainNodeName: 'Transmisor Montauk',
    status: 'en_curso',
    summary:
      'Sesión plenaria presencial. Indagación sobre la sincronización de microondas en Camp Hero, anomalías de memoria colectiva y supuestos protocolos de teletransportación durante el eclipse de 1983.',
    durationMin: 25,
    slidesUrl: 'https://docs.google.com/presentation/d/demo-s04',
    slideCount: 28,
    routeUsedSummary: 'N-03 -> N-04 (Puente narrativo continuo)',
    cliffhanger:
      '¿Quién apagó el generador auxiliar cuando los archivos desaparecieron en la tormenta de 1984?',
    nextProposedNodeIds: ['N05', 'N07'],
  },
];

export const INITIAL_CANON: CanonEntry[] = [
  {
    id: 'CANON-01',
    codex: 'CANON-01',
    sessionId: 'S01',
    sessionNumber: '01',
    text: 'El Proyecto Paperclip operó bajo dos nóminas paralelas; los científicos de la división oculta reportaban a un comité sin sello oficial.',
    proponentName: 'Elena R.',
    proponentRole: 'Archivista Forense',
    date: '28-SEP-1989',
    status: 'vigente',
    version: '1.0',
    votesFor: 5,
    votesAgainst: 0,
    votesAbstain: 0,
    relatedNodeIds: ['N01', 'N02'],
    nodeRelationSummary: 'N-01 (Paperclip) ➔ N-02 (MKUltra Montreal)',
    chronologicalImpact: '1946 - 1954 // Desclasificación Nivel 5',
    auditBlockHash: 'SHA256//AC-00101-ER',
  },
  {
    id: 'CANON-02',
    codex: 'CANON-02',
    sessionId: 'S02',
    sessionNumber: '02',
    text: 'Los experimentos del Subproyecto 68 en Montreal utilizaban cintas de repetición con frecuencias binaurales de abeto montañés para inducir recuerdos de paisajes nevados.',
    originalText:
      'Los experimentos del Subproyecto 68 en Montreal utilizaban cintas de repetición electrostáticas sin modulación para borrar los traumas infantiles de agentes durmientes.',
    proponentName: 'Elena R.',
    proponentRole: 'Archivista Forense',
    enmendedBy: 'Lucas V.',
    enmendedSession: 'Sesión 03',
    amendmentReason:
      'Se requería armonizar la frecuencia acústica con el caso Roswell y la resonancia con los abetos de la cordillera Blackwood descubiertos en la Sesión 03.',
    date: '14-OCT-1989',
    status: 'enmendada',
    version: '2.0',
    votesFor: 4,
    votesAgainst: 1,
    votesAbstain: 0,
    relatedNodeIds: ['N02', 'N05', 'N03'],
    nodeRelationSummary: 'N-02 (MKUltra) ➔ N-05 (Bosque Blackwood) ➔ N-03 (Roswell Crash)',
    chronologicalImpact: '1953 - 1964 // Revisión de Actas Salón',
    auditBlockHash: 'SHA256//AC-09224-LK',
    dissentNote: 'Carlos M. solicitó preservar el texto v1.0 en el apéndice de auditoría.',
  },
  {
    id: 'CANON-03',
    codex: 'CANON-03',
    sessionId: 'S03',
    sessionNumber: '03',
    text: 'El material metálico recuperado en Wright-Patterson no era aeroespacial, sino una aleación memética que reacciona a la presencia humana.',
    proponentName: 'Sofía G.',
    proponentRole: 'Criptología',
    date: '14-OCT-1989',
    status: 'vigente',
    version: '1.0',
    votesFor: 4,
    votesAgainst: 1,
    votesAbstain: 1,
    relatedNodeIds: ['N03', 'N04'],
    nodeRelationSummary: 'N-03 (Roswell) ➔ N-04 (Hangar 18)',
    chronologicalImpact: '1947 - 1983 // Protocolo de Manipulación Biológica',
    auditBlockHash: 'SHA256//AC-08819-SG',
    dissentNote: "Carlos M. votó 'No' alegando contradicción con la balística de fragmentos.",
  },
  {
    id: 'CANON-00-EX',
    codex: 'CANON-00-EX',
    sessionId: 'S02',
    sessionNumber: '02',
    text: 'El testigo de la caseta de guardia en White Sands confirmó la presencia de personal de habla alemana la noche del 16 de julio de 1945.',
    proponentName: 'Carlos M.',
    proponentRole: 'Terreno',
    date: '02-OCT-1989',
    status: 'retirada',
    version: '0.9',
    votesFor: 1,
    votesAgainst: 4,
    votesAbstain: 0,
    relatedNodeIds: ['N01'],
    nodeRelationSummary: 'N-01 (Paperclip) // Descartado de la Trama',
    chronologicalImpact: 'Anulado en Sesión #04 por contradicción directa con el registro de guardia',
    auditBlockHash: 'SHA256//AC-EXP-002-CM',
    dissentNote: 'Revocada formalmente por asamblea tras peritaje de firmas.',
  },
];

export const INITIAL_CLAIMS: Claim[] = [
  {
    id: 'C01',
    nodeId: 'N04',
    sessionId: 'S04',
    code: 'EXP-ARC-01 // NARA RG-342',
    title: 'Existencia de la estación de radar militar AN/FPS-35 en Camp Hero',
    text: 'Instalación de radar de largo alcance SAGE comisionada en Montauk Point para vigilancia aérea de la Guerra Fría. Activa formalmente entre 1958 y 1981 con magnetrones de 425 MHz.',
    truthLayer: 'HECHO',
    author: 'Archivos Nacionales (NARA), Washington D.C.',
    sourceText: 'Expediente desclasificado NARA RG-342 / DoD 1982',
    status: 'confirmado',
    dateStr: '1982',
  },
  {
    id: 'C02',
    nodeId: 'N04',
    sessionId: 'S04',
    code: 'EXP-GAO-84-LONGISLAND',
    title: 'Desvío de fondos no auditados del presupuesto de defensa en Long Island',
    text: 'Los balances de cuentas de mantenimiento de infraestructura costera de 1978 a 1983 reflejan discrepancias no reconciliadas por un total de 4.2 millones de dólares adjudicados a contratistas encubiertos sin asignación específica.',
    truthLayer: 'HECHO',
    author: 'Auditoría Financiera del Congreso (Subcomité GAO-84)',
    sourceText: 'Informe GAO/NSIAD-84-118',
    status: 'confirmado',
    dateStr: '1984',
  },
  {
    id: 'C03',
    nodeId: 'N04',
    sessionId: 'S04',
    code: 'DECLARACIÓN // TEST-01',
    title: 'Alteración de la percepción del tiempo en residentes locales (1983)',
    text: 'Preston Nichols sostiene que los pulsos emitidos a 425 MHz por la antena triangular alteraron de forma deliberada el lóbulo temporal de los pescadores y residentes de Montauk, induciendo lapsos de amnesia colectiva y pesadillas compartidas en agosto de 1983.',
    truthLayer: 'AFIRMACIÓN',
    author: 'Preston B. Nichols',
    sourceText: 'The Montauk Project: Experiments in Time (1992)',
    status: 'conjetura',
    dateStr: '1992',
  },
  {
    id: 'C04',
    nodeId: 'N04',
    sessionId: 'S04',
    code: 'DECLARACIÓN // TEST-02',
    title: "Salto al año 2137 mediante interfaz de la 'Silla de Montauk'",
    text: 'Al Bielek afirma haber sido sometido a una interfaz cerebro-computadora financiada por ITT en un búnker subterráneo, la cual amplificaba firmas biomagnéticas hasta abrir un vórtice hiperespacial que supuestamente lo desplazó al siglo XXII.',
    truthLayer: 'AFIRMACIÓN',
    author: 'Al Bielek',
    sourceText: 'Conferencia MUFON (1990)',
    status: 'conjetura_extrema',
    dateStr: '1990',
  },
];

export const INITIAL_SOURCES: Source[] = [
  {
    id: 'SRC-01',
    code: 'NARA-RG-330-E45',
    title: 'Dossier de Traslado de Especialistas en Cohetes de Peenemünde',
    author: 'Joint Intelligence Objectives Agency (JIOA)',
    date: '1946',
    type: 'documento_oficial',
    url: 'https://catalog.archives.gov/id/paperclip',
    note: 'Listas de transporte militar de White Sands con sellos originales de desclasificación.',
    addedBy: 'Carlos M.',
    nodeId: 'N01',
    truthLayer: 'HECHO',
  },
  {
    id: 'SRC-02',
    code: 'SEN-CH-1977-MKU',
    title: 'Transcripción de la Audiencia del Comité Church sobre MKUltra',
    author: 'Senado de los Estados Unidos (Comité Selecto de Inteligencia)',
    date: 'Agosto 1977',
    type: 'foia',
    url: 'https://www.intelligence.senate.gov/mkultra',
    note: 'Testimonio del director Stansfield Turner sobre la destrucción masiva de archivos en 1973.',
    addedBy: 'Sofía G.',
    nodeId: 'N02',
    truthLayer: 'HECHO',
  },
  {
    id: 'SRC-03',
    code: 'AFOSR-TR-84-0199',
    title: 'Esquema de Modulación de Antena de Radar SAGE AN/FPS-35',
    author: 'Air Force Office of Scientific Research',
    date: '1984',
    type: 'croquis',
    url: 'https://catalog.archives.gov/id/sage-radar',
    note: 'Planos de cableado y bobinas Helmholtz instaladas en la base del transmisor.',
    addedBy: 'Elena R.',
    nodeId: 'N04',
    truthLayer: 'HECHO',
  },
  {
    id: 'SRC-04',
    code: 'TEST-NICHOLS-CASSETTE',
    title: 'Grabación en Cinta de Preston Nichols en Long Island Sound',
    author: 'Preston B. Nichols / Entrevista de campo',
    date: '1989',
    type: 'audio',
    note: 'Cinta magnetofónica de 45 minutos describiendo la sintonía a 425 MHz.',
    addedBy: 'Carlos M.',
    nodeId: 'N04',
    truthLayer: 'AFIRMACIÓN',
  },
  {
    id: 'SRC-05',
    code: 'FOIA-MJ12-CUTLER',
    title: 'Memorándum Cutler-Twining (Copia de Archivo)',
    author: 'Robert Cutler / Asistente Presidencial',
    date: '14 Julio 1954',
    type: 'documento_oficial',
    note: 'Documento en disputa sobre la reunión especial de Majestic-12.',
    addedBy: 'Elena R.',
    nodeId: 'N07',
    truthLayer: 'AFIRMACIÓN',
  },
];

export const INITIAL_LOOSE_ENDS: LooseEnd[] = [
  {
    id: 'LE-01',
    code: 'CABO-01 // REGISTRO FARO',
    sessionId: 'S02',
    sessionNumber: '02',
    text: 'La frecuencia de 435 MHz detectada en los registros del faro',
    detail:
      'Bitácora manuscrita del farero de Montauk Point registra apagones cíclicos sincronizados con pulsos de radio de alta intensidad en septiembre de 1983.',
    relatedNodeIds: ['N04', 'N08'],
    authorName: 'Carlos M.',
    status: 'abierto',
    openedDate: '05 Oct 2026',
    priority: 'urgente',
  },
  {
    id: 'LE-02',
    code: 'CABO-02 // DOCUMENTAL',
    sessionId: 'S03',
    sessionNumber: '03',
    text: 'El memorándum quemado firmado por “Majestic-4”',
    detail:
      'Fragmento calcinado recuperado de la chimenea de la base auxiliar. Solo sobreviven los nombres de dos oficiales de enlace y un sello de cera de despacho.',
    relatedNodeIds: ['N03', 'N07'],
    authorName: 'Agente Cooper',
    status: 'retomado',
    openedDate: '12 Oct 2026',
    priority: 'prioritario',
  },
  {
    id: 'LE-03',
    code: 'CABO-03 // AUDIO GLASTONBURY',
    sessionId: 'S03',
    sessionNumber: '03',
    text: 'La cinta magnética sin etiquetar hallada en la cabaña del lago',
    detail:
      'Grabación de 14 minutos que reproduce una conversación en alemán técnico intercalada con una frecuencia sostenida de 7.83 Hz.',
    relatedNodeIds: ['N01', 'N12'],
    authorName: 'Lucas V.',
    status: 'abierto',
    openedDate: '12 Oct 2026',
    priority: 'secundario',
  },
  {
    id: 'LE-04',
    code: 'CABO-04 // BITÁCORA DE VUELO',
    sessionId: 'S01',
    sessionNumber: '01',
    text: 'El manifiesto del vuelo C-47 con rumbo a Goose Bay (1947)',
    detail:
      'Registro de aduanas canadienses con tres pasajeros listados bajo códigos alfanuméricos sin pasaporte civil.',
    relatedNodeIds: ['N01', 'N02'],
    authorName: 'Elena R.',
    status: 'resuelto',
    openedDate: '28 Sep 2026',
    resolvedSessionId: 'S02',
    priority: 'secundario',
  },
];

export const INITIAL_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'AUD-01',
    timestamp: '2026-10-14T22:15:00Z',
    timeLabel: '14-OCT-2026 // 22:15',
    actor: 'Lucas V.',
    action: 'Enmienda de Canon',
    entity: 'CANON-02',
    entityId: 'CANON-02',
    summary:
      'Lucas V. propuso enmienda formal a CANON-02. Votación concluida con 4 votos afirmativos contra 1. Canon actualizado a V2.0.',
    blockHash: '#AC-09224-LK',
    type: 'enmienda',
  },
  {
    id: 'AUD-02',
    timestamp: '2026-10-14T21:05:00Z',
    timeLabel: '14-OCT-2026 // 21:05',
    actor: 'Sofía G.',
    action: 'Registro de Canon',
    entity: 'CANON-03',
    entityId: 'CANON-03',
    summary:
      'Sofía G. sometió a asamblea la naturaleza memética de la aleación en Wright-Patterson. Aprobado por mayoría absoluta (4/1/1).',
    blockHash: '#AC-08819-SG',
    type: 'canon',
  },
  {
    id: 'AUD-03',
    timestamp: '2026-10-02T23:40:00Z',
    timeLabel: '02-OCT-2026 // 23:40',
    actor: 'Agente Cooper',
    action: 'Cierre de Sesión',
    entity: 'Sesión #02',
    entityId: 'S02',
    summary:
      'Sesión #02 declarada cerrada formalmente por el Anfitrión Cooper. Todos los lazos del tablero bloqueados contra escritura.',
    blockHash: '#SES-02-END',
    type: 'cierre',
  },
  {
    id: 'AUD-04',
    timestamp: '2026-09-28T20:10:00Z',
    timeLabel: '28-SEP-2026 // 20:10',
    actor: 'Elena R.',
    action: 'Canon Fundacional',
    entity: 'CANON-01',
    entityId: 'CANON-01',
    summary:
      'Elena R. introdujo CANON-01 sobre la estructura dual de nóminas de Paperclip. Unanimidad de mesa (5/5).',
    blockHash: '#AC-00101-ER',
    type: 'fundacional',
  },
];
